project:
  type: book
  output-dir: docs


book:
  title: "Open Science: Wie sich die Wissenschaft öffnet"
  language: de-DE
  author: "Lukas Röseler"
  description: "Vertrauenskrise, Replikationsrevolution, und Open Science einfach und umfangreich erklärt"
  reader-mode: true

  page-footer:
    left: |
       Röseler, L. (in preparation). Open Science: Wie sich die Wissenschaft öffnet (0.5th ed.). https://doi.org/10.17605/OSF.IO/2QXWV
    right: |
      Mithilfe von <a href="https://quarto.org/">Quarto</a> erstellt. Lizenz: CC-By Attribution 4.0 International.
  favicon: images/favicon_os.jpg
  cookie-consent: false
  site-url: lukasroeseler.github.io/opensciencebuch/
  repo-url: https://github.com/LukasRoeseler/opensciencebuch
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd

    - about.qmd

    - part: einleitung.qmd
      chapters:
        - wasistopenscience.qmd
        - umgehenmitopenscience.qmd

    - part: geschichte.qmd
      chapters:
        - anfänge.qmd
        - bestandsaufnahme.qmd
        - wandel.qmd
        - struktur.qmd
        
    - part: probleme.qmd
      chapters:
        - probleme_system.qmd
        - probleme_karriere.qmd
        - probleme_methoden.qmd
        - probleme_theorien.qmd
        - probleme_epistemische.qmd
        
    - part: lösungen.qmd
      chapters:
        - lösungen_system.qmd
        - lösungen_methoden.qmd
        - lösungen_theorien.qmd
        - lösungen_welt.qmd
        
    - part: fazit.qmd
  
  downloads: [pdf]
        

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Lukas Röseler"
    callout-appearance: simple
    css: styles.css
    number-sections: false
  pdf:
    documentclass: scrreprt
    cover-image: cover.jpg

editor: visual