project:
  type: book
  output-dir: _site

book:
  title: "Open Science: Wie sich die Wissenschaft öffnet"
  reader-mode: true

  page-footer:
    left: |
      Autor: Lukas Röseler.
    right: |
      Das Buch wurde mithilfe von <a href="https://quarto.org/">Quarto</a> erstellt.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: lukasroeseler.github.io/opensciencebuch/
  repo-url: https://github.com/LukasRoeseler/opensciencebuch
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd

    - about.qmd

    - part: einleitung.qmd
      chapters:
        - wasistopenscience.qmd
        - umgehenmitopenscience.qmd

    - part: geschichte.qmd
      chapters:
        - anfänge.qmd
        - bestandsaufnahme.qmd
        - wandel.qmd
        - beimerstenversuch.qmd
        - struktur.qmd
        
    - part: probleme.qmd
      chapters:
        - probleme_system.qmd
        - probleme_karriere.qmd
        - probleme_methoden.qmd
        - probleme_theorien.qmd
        - probleme_epistemische.qmd
        - probleme_krieg.qmd
        
    - part: lösungen.qmd
      chapters:
        - lösungen_system.qmd
        - lösungen_methoden.qmd
        - lösungen_theorien.qmd
        - lösungen_welt.qmd
        
    - part: fazit.qmd
        
  downloads: [pdf, epub]
        

format:
  html:
    theme:
      - cosmo
    code-link: true

    author-meta: "Lukas Röseler"
    callout-appearance: simple

editor: visual