---
title: "Über das Buch"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Wissenschaft wird zu einem maßgeblichen Teil von den Mitgliedern einer Gesellschaft finanziert, beispielsweise über Steuergelder. Das bedeutet, eine Gemeinschaft fördert einzelne Personen, um ein tieferes Verständnis von sich und der Welt zu erlangen und im Gegenzug Unterstützung bei der Lösung verschiedener Probleme zu erhalten. Dadurch sind Wissenschaftler\*innen der Gesellschaft in einem gewissen Maße Rechenschaft schuldig. Dabei geht es nicht darum, dass jede wissenschaftliche Erkenntnis notwendigerweise Früchte tragen muss, aber, dass sie wissenschaftlichen Qualitätskriterien entspricht und zumindest für andere Forschende nachvollziehbar und nachprüfbar ist. Inwiefern das in verschiedenen Disziplinen der Fall ist und wie Personen sich dafür einsetzen, diese Rechenschaft zu ermöglichen, möchte ich in diesem Buch darlegen.

Dieses Buch soll selbst ein Teil der offenen Wissenschaft sein. Im Kontext der Probleme und Lösungen erkläre ich, wie der Beruf *Wissenschaftler\*in* aussieht, wie das Wissenschaftssystem funktioniert, und erörtere an Beispielen auszugsweise wissenschaftliche Debatten. Zur Offenheit gehört auch, dass das Buch frei zugänglich ist.

::: callout-note
## Danksagungen

Dieses Buch wäre nicht möglich gewesen ohne die Unterstützung meiner Frau Jessica. Von ihr nährt sich mein Optimismus und meine Kraft, mich für eine offene, nachvollziehbare, und gerechte Wissenschaft einzusetzen.

Ich danke Lena Röseler, Celina Wagner, Helga Röseler, und Anna Wentzel für das Korrekturlesen und die unzähligen Verbesserungsvorschläge, Wibke Fellermann für Empfehlungen zu Stil und Layout, und Victoria Moser für die Überarbeitung der Abbildungen.

In Beispielen, Hinweisen, und Anmerkungen stütze ich mich zudem auf zahlreiche Beispiele, die ich mit Kolleginnen, Kollegen, Freundinnen und Freunden diskutiert habe. Ich danke Daniel Wolf, Johannes Leder, Thomas Lösch, Matthias Borgstede, Astrid Schütz, Ulrike Starker, Georg Felser, Viola Voß, Mitja Back, Jan H. Höffler, Helene Richter, Janik Goltermann, Gilad Feldman, Flavio Azevedo, Lukas Wallrich und vielen anderen für die spannenden Gespräche!
:::

::: callout-note
## Nutzung von KI

Claude Sonnet 5 wurde benutzt, um das Layout anzupassen und Rechtschreibfehler zu identifizieren. Eine in Bearbeitung befindliche englische Übersetzung wurde ebenfalls mit Claude Sonnet 5 erstellt.
:::

------------------------------------------------------------------------
