---
title: "Anfänge einer Revolution"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Um das Jahr 2010 herum häuften sich in der Psychologie Ereignisse, die für sich genommen als Einzelfälle abgetan werden konnten, gemeinsam aber ein negatives Bild der Wissenschaft zeichneten.

### Stapel-Affäre {unnumbered.=""}

Durch einen Zufall entdeckten Nachwuchswissenschaftler im Jahr 2011, dass die Daten einer Studie ihres Kollegen, Diederik Stapel, von niemandem jemals erhoben wurden. Sie waren ausgedacht bzw. fabriziert. Stand Juli 2024 wurden 58 von Stapels Fachartikel identifiziert und zurückgezogen, deren Daten fabriziert oder geschönt wurden.[^anfänge-1] Wissenschaftliche Institutionen wie der Begutachtungsprozess von Artikeln durch Fachkolleg\*inen, deren Zweck die Qualitätssicherung war, hatten versagt. Seit dem Vorfall sind einige weitere Fälle bekannt geworden, teilweise durch erneute Analyse von Daten der jeweiligen Studien [@o2021honesty] und oft durch Whistleblower, also durch wissende Personen, die zu ihrem Schutz anonym bleiben wollen. Umfragen in den Niederlanden unter Forschenden haben ergeben, dass Fälschung oder Schönigung von Daten von bis zu 10% aller Personen durchgeführt wird [@Gopalakrishna.2021b]. Dabei ist zu beachten, dass Studien durch gefälschte Daten besonders innovativ, überraschend, oder klar werden - Eigenschaften, die die Veröffentlichung in einer Fachzeitschrift wahrscheinlicher machen.

[^anfänge-1]: Mittels der Retraction Database lassen sich nach Thema, Autor\*in, Zeitschrift, usw. zurückgezogene Artikel durchsuchen: http://retractiondatabase.org/

### Bem: Die Zukunft erfühlen {unnumbered=""}

Kurze Zeit später veröffentliche Daryl Bem, bekannt durch grundlegende psychologisch-philosophische Theorien wie der Self-Perception-Theory [@Bem.1967], den Befund, dass Personen die Zukunft vorhersagen können [@Bem.2011]. Genauer gesagt, können manche Personen unter bestimmten Voraussetzungen die Zukunft vorhersagen. In acht Studien fand die Forschendengruppe heraus, dass Personen Vorhersagen über erotische Bilder machen konnten. Die Ergebnisse wurden in der hoch angesehenen Fachzeitschrift *Journal of Personality and Social Psychology* veröffentlicht. Vielen Psycholog\*innen war sofort klar: Entweder, grundlegende Annahmen ihres Weltbildes waren falsch ("Personen können nicht die Zukunft vorhersagen") oder es stimmte etwas mit den Ergebnissen nicht. Mehrere Forschende versuchten sich daran zu erklären, wie es zu den Ergebnissen kam. Analysen der veröffentlichten Daten mit alternativen statistischen Methoden führten zur selben Schlussfolgerung [@Wagenmakers.2011], Replikationen durch unabhängige Forschende schlugen jedoch fehl [@robinson2011not, @muhmenthaler2022future, @roe2012feeling].

### Bargh: Beeinflussen durch *Priming* {unnumbered.=""}

Seine Studien wurden im Marketing gefeiert und als neurowissenschaftliche Erkenntnisse verkauft: Wer ein heißes Getränk (im Vergleich zu einem kalten) trinkt, schätzt andere Personen als "wärmer" (großzügig, rücksichtsvoll) ein [@williams2008experiencing]. Wer Anagramme löst, die etwas mit hohem Alter zu tun haben (z.B. GEPLEHIMEF statt PFLEGEHEIM, URGA statt GRAU, oder zum selbst probieren GHOSTECK), geht danach in langsamerem Tempo [@bargh1996automaticity]. Viele dieser Studien wurden repliziert: Forschenden fiel in der Anagramme-Studie auf, dass Bargh und Kolleg\*innen die Zeit mit Stoppuhren gemessen hatten und dabei wussten, welche Person die "Alt"-Wörter und welche die neutralen Anagramme gelöst hatten - dabei lernt jede\*r Psychologie-Studierende im ersten Jahr, dass das nicht der Fall sein sollte und Versuchsleiter\*innen "blind" gegenüber dem Untersuchungszweck und der Zuordnung der Personen zu den Gruppen sein sollte. In ihrer Replikation [@Doyen.2012] ließen Doyen und Kolleg\*innen die Zeit mit Lichtschranken erfassen und maßen selbst wie Bargh et al. in der Originalstudie. Bei der problematischen Messung kam dasselbe raus, die Lichtschranken, denen vorher nicht verraten wurde, welche Hypothese mit ihnen untersucht werden sollten und welche Personen welche Anagramme lösen mussten, konnten den Effekt jedoch nicht replizieren.

::: callout-important
## Wichtige Ereignisse jenseits der Psychologie

In der Verhaltensbiologie zeigten @Crabbe1999-ao bereits viel früher, dass Befunde zum Einfluss der Gene auf das Verhalten stark davon abhingen, in welchem Labor die Mäuse untersucht wurden. Während Verbesserungen im Forschungsprozess seitdem immer wieder gefordert wurden [@Kafkafi2018-yr] blieb eine Revolution wie in der Psychologie aus.

Ein etwas anderes Problem ergab sich im Rahmen der Sequenzierung der menschlichen DNS: Dort beantragten Unternehmen noch während des Erforschungsprozess die Rechte daran (*Intellectual Property*). Die negativen sozialen und wissenschaftlichen Folgen wurden früh diskutiert [@Moore2000-pr] und sind noch immer [Teil von wissenschaftlichen und politischen Diskussionen](https://www.ip.mpg.de/en/research/research-news/position-statement-on-new-genomic-techniques-and-intellectual-property-law.html).
:::

### Literatur
