---
title: "Beim ersten Versuch klappt es nie: Der Paradigmenwechsel in der Psychologie"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Ein Paradigmenwechsel ist vergleichbar mit einem Kippbild die dem Hase-Ente-Bild (**Abbildung 1**) wie es zum Beispiel Wittgenstein (Tractatus logico-philosophicus, 1984) gezeichnet hat. Bis zu einem gewissen Punkt sind sich alle einig, dass es ein Hase ist. Doch nach und nach kommen Erkenntnisse und Perspektiven hinzu. Der Punkt wird überschritten, die Ente ist anerkannt, und niemand würde es mehr für einen Hasen halten. Beim Hase-Ente-Bild lässt sich natürlich beliebig hin und her springen. Beim wissenschaftlichen Fortschritt kommt neues Wissen hinzu und eine Rückkehr ist nur noch schwer möglich.

**Abbildung 1\
** *Hase-Ente-Kippbild frei nach Wittgenstein: Die Quader auf der linken Seite können entweder als Schnabel einer nach links blickenden Ente oder Ohren eines nach rechts blickenden Hasen interpretiert werden.*

Tatsächlich wurde ich von Beginn meiner Methodenausbildung an darin geschult, entsprechend des amtierenden psychologischen Paradigmas mit fehlgeschlagenen Replikationen umzugehen. Ich begann mein Studium bevor die Replikationskrise sich herauskristallisierte. Bei der ersten Studie, an der ich beteiligt war, replizierten wir den Befund, dass bunte Mengen in ihrer Anzahl weniger aussahen als einfarbige Mengen. Im Rahmen der Konsumentenpsychologie ist das hinsichtlich Slogans wie "viele viele bunte Smarties" etwas kontraintuitiv, es lässt sich aber gestaltpsychologisch plausibel darlegen. Nachdem eine Vorgruppe das Gegenteil herausfand, nämlich das bunte Smarties tatsächlich nach mehr aussahen als einfarbige Smarties, konnten wir in zwei eigenen Studien nichts vom beiden nachweisen. Egal ob die Teller, Tassen, oder Schalen, die wir den Leuten gaben, aus blauen, roten, gelben, oder bunten Schokolinsen bestanden: Unsere Versuchspersonen schätzten immer unabhängig von der Farbe. In den folgenden Jahren durfte ich als Tutor dann weitere Replikationsversuche durchführen. Der betreuende Professor erklärte: Ich habe es eigentlich noch nie erlebt, dass die Hypothese gleich beim ersten Versuch bestätigt wird. Nach jedem Experiment ist man schlauer und weiß, was man nächstes Mal besser machen muss. Es ist ganz natürlich, dass es ein paar Versuche dauert, bis man weiß, wie sich die Hypothese bestätigen lässt. Nachdem wir 5 (?XXX) Studien mit insgesamt über XXX Versuchspersonen durchgeführt hatten, die Autoren der Originalstudie um Rat gebeten haten, haufenweise Schokolinsen verzehrt hatten, und die Hypothese über alle Studien hinweg nicht bestätigt wurde, hatte ich das Vertrauen in den Befund verloren.

Ungefähr sechs Jahre später dachte ich während meiner Promotionszeit an die Studien zurück und diskutierte mit dem Professor. Im Rahmen der Replikationskrise war klar: Wenn man mehrere Experimente durchführt und die Hypothese eigentlich falsch ist, wird alleine durch den Zufall ab und zu trotzdem die Hypothese bestätigt. Das ist vergleichbar damit, dass selbst eine faire Münze sechs Mal hintereinander auf derselben Seite landen kann. Es passiert nicht oft, wenn man jedoch 10 Münzen gleichzeitig sechs Mal wirft, ist es nicht selten, dass eine davon sechs Mal auf derselben Seite landet. Aus dieser Perspektive hat das Zitat, dass die Ergebnisse beim ersten Versuch eigentlich nie so rauskommen, wie man es sich wünscht, einen bitteren Beigeschmack. Wenn die Hypothese falsch ist, ist es tatsächlich unwahrscheinlich, dass sie dennoch bestätigt wird. Nicht aber, wenn man mehrere Studien hintereinander durchführt. Dann ist es sogar zu erwarten, dass irgendwann eine Studie die Hypothese - auch wenn sie eigentlich falsch ist (!) - bestätigt.
