---
title: "Einleitung"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

# Nachvollziehbare Wissenschaft

Beginnen wir mit einem hypothetischen Beispiel: In Deutschland [könnte](https://www.tagesschau.de/inland/innenpolitik/organspende-gesetz-100.html) der Standard zur Organspende verändert werden. So wie es momentan ist, könnten auch nach der Veränderung alle weiterhin frei entscheiden, ob sie ihre Organe spenden möchten oder nicht. Wie in Österreich wäre die Alternative eine "Widerspruchslösung", das heißt, alle Personen sind per se Organspender und müssen diesem Status aktiv widersprechen. Beim aktuellen Modell müssen sie stattdessen aktiv zustimmen (zum Beispiel durch Bestellen eines [Organspendeausweises](www.organspende-info.de/organspendeausweis-download-und-bestellen/)).

Die Basis für eine solche hypothetische und politische Entscheidung wäre ein wissenschaftlicher Befund: Bei der Widerspruchslösung ist der Anteil an Organspender\*innen[^einleitung-1] höher, als wenn sich Personen aktiv um den Status "Organspender*\**in" bemühen müssen. Den ursprünglichen Befund berichteten @Johnson2003-yb. Fast 20 Jahre später konnten @Chandrashekar2023-gm den Befund mit neu erhobenen Daten erneut nachweisen, ihn also *replizieren*. Alle Informationen zur Replikation lassen sich [online nachlesen](https://open.lnu.se/index.php/metapsychology/article/view/3108) und ihre Ergebnisse sind [online vollständig einsehbar](https://osf.io/8wd2b/). Mit kostenlosen Programmen lässt sich alles nachrechnen und prüfen, was seitens der Fachzeitschrift, in der die Ergebnisse veröffentlicht wurden, bereits von einer unabhängigen Person getan wurde. Darüber hinaus gilt der Effekt nicht nur für Organspende sondern auch für alle möglichen anderen Entscheidungen von Menschen. Das allgemeine Phänomen heißt *Default Effect*. Die *wissenschaftliche Basis* der politischen Entscheidung ist hier also überprüfbar und nachvollziehbar.

[^einleitung-1]: Die Entscheidung, auf das generische Maskulin zugunsten des Gender-Sternchens zu verzichten, beruht auf der wissenschaftlichen Tatsache, dass sich damit besser das Ziel erreichen lässt, Personen verschiedener Geschlechter gleichermaßen anzusprechen[@Brohmer2024-wn].

Die Transparenz des wissenschaftlichen Befundes ist in diesem Beispiel deutlich gegeben. Doch leider ist das nicht repräsentativ für Wissenschaft. Häufig lassen sich Forschungsbefunde nicht einfach nachlesen, sondern Forschungsberichte müssen von Fachzeitschriften gekauft werden (bzw. bei den Autor\*innen angefragt per Mail werden), Daten müssen angefragt werden, und Ergebnisse lassen sich nur mithilfe von kostspieligen Programmen nachrechnen. Diese Offenheit spielt zur Zeit eine besondere Rolle: Es herrscht eine Skepsis gegenüber Wissenschaft [@Sultan2024-qu] und politische Entscheidungen über Heizungen, Impfungen, Ernährung, oder Mobilität stützen sich auf Wissenschaft, werden gleichzeitig aber als falsch, kostspielig, oder bedrohlich wahrgenommen. Irreführende oder schlicht falsche Informationen werden verbreitet und Menschen nutzen künstliche Intelligenz (Large Language Models), welche auf potenziell falschen Informationen basieren und nicht fähig sind, die Herkunft der Informationen anzugeben.

Wie sich die Offenheit von Wissenschaft ändert, was Forschende auf der ganzen Welt dafür tun, Wissenschaft zu öffnen, und welche Lösungsvorschläge diesbezüglich diskutiert und umgesetzt werden, ist Gegenstand dieses Buches. Ein Überblick über Dimensionen von Offenheit in Anlehnung an @Silveira2023-xq ist in der folgenden Tabelle. Dabei befinden sich viele wissenschaftliche Disziplinen zwischen den Extrema der "klassischen Wissenschaft" und der "offenen Wissenschaft". Letztere stellt dabei das Ideal dar, also den Zustand, der für wissenschaftlichen Fortschritt am besten wäre.

| Dimension                                                              | Klassische Wissenschaft                                                                                                                                                                                                                                                                                                                                                                            | Offene Wissenschaft                                                                                                                                                                                                            |
|------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Offener Zugang (Open Access)                                           | Forschungsartikel und Bücher müssen gekauft oder geliehen werden.                                                                                                                                                                                                                                                                                                                                  | Forschungsartikel und Bücher sind kostenlos online verfügbar.                                                                                                                                                                  |
| Offene Materialien und Daten                                           | Materialien und Daten, auf Basis derer wissenschaftliche Befunde kommuniziert werden, werden nicht, nur auf Nachfrage, oder mit starker Verzögerung geteilt.                                                                                                                                                                                                                                       | Materialien und Daten werden im Zuge der Veröffentlichung des Forschungsberichts veröffentlicht.                                                                                                                               |
| Offene Bewertung von Forschenden, Universitäten, und Fachzeitschriften | Wissenschaft wird auf Basis von intransparenten und manipulierbaren Metriken bewertet.                                                                                                                                                                                                                                                                                                             | Wissenschaft wird auf Basis von objektiven Kriterien, die eng mit der wissenschaftlichen Qualitätssicherung zusammenhängen, bewertet.                                                                                          |
| Offene Lehre                                                           | Wissen zu erwerben ist kostspielig und erfordert die Anwesenheit an bestimmten Orten zu bestimmten Zeiten.                                                                                                                                                                                                                                                                                         | Lehrmaterialien und Kurse sind kostenlos online verfügbar, Lehre wird (auch) online durchgeführt, es wird darauf geachtet, Materialien barrierearm zu gestalten.                                                               |
| Offene Innovation, "Big Team Science"                                  | Gruppen von Forschenden arbeiten in einem starken Wettkampf isoliert an ähnlichen Problemen.                                                                                                                                                                                                                                                                                                       | Forschende kooperieren international und interdisziplinär und bündeln Ressourcen.                                                                                                                                              |
| Offene Infrastruktur                                                   | Im Wissenschaftsalltag sind Forschende auf Gelder für Computerprogramme oder Veröffentlichungen angewiesen.                                                                                                                                                                                                                                                                                        | Der Prozesse der Forschung und Qualitätssicherung sind unabhängig von kommerziellen Verlagen und werden von Wissenschaftler\*innen und Universitäten eigenständig und nachhaltig organisiert.                                  |
| Bürger\*innen- bzw. partizipative Wissenschaft                         | Die Beteiligung von Bürger\*innen in der Wissenschaft ist von nachrangiger Bedeutung.                                                                                                                                                                                                                                                                                                              | Bürger\*innen werden aktiv in den Forschungsprozess einbezogen und bereichern die Wissenschaft.                                                                                                                                |
| Offener wissenschaftlicher Diskurs                                     | Wissenschaftliche Kritik wird als persönliche Kritik aufgefasst, schadet der wissenschaftlichen Karriere, und hat persönliche Gegenschläge zur Folge. Gutachten wissenschaftlicher Artikel sind anonym, werden der wissenschaftlichen Leistung nicht angerechnet, und nur durch wenige Personen einsehbar. Kommentare zu Forschungsartikeln werden selten und nur nach langer Zeit veröffentlicht. | Es herrscht eine wertschätzende und konstruktive Fehlerkultur, Gutachten sind öffentlich und nur bei Wunsch anonym. Wissenschaftliche Artikel lassen sich innerhalb weniger Minuten kommentieren.                              |
| Replikationsforschung                                                  | Neue Studien müssen neue Fragen untersuchen. Studien, die bereits nachgewiesene Dinge erneut prüfen werden nicht veröffentlicht: Fehlgeschlagenen Replikationsversuchen werden methodische Probleme unterstellt, erfolgreiche Replikationen werden als uninformativ erachtet..                                                                                                                     | Vergangene Befunde werden hinterfragt und unabhängige Forschende versuchen, sie erneut mit neuen Daten nachzuweisen, also zu replizieren. Zeitschriften veröffentlichen diese Replikationsversuche unabhängig von Ergebnissen. |

: Dimensionen von Offenheit in der Wissenschaft

## Literatur
