---
title: "Epistemische Probleme"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Epistemologie heißt Erkenntnislehre und ist ein Teilgebiet der Philosophie. Darin wird diskutiert, wie Wissenschaft funktioniert, wie Wissen produziert werden kann, oder worin der Unterschied zwischen wissen und glauben liegt. Epistemologische Erklärungsansätze für Replikationsfehlschläge übersteigen die Probleme, die durch das wissenschaftliche System oder wissenschaftliche Methoden entstanden sind, haben aber auch andere Prüfbarkeitsansprüche. Während wissenschaftstheoretische Ansätze teilweise empirisch (also durch Beobachtungen) prüfbare Vorhersagen erlauben, lässt sich über die philosophischen Probleme nur nachdenken und diskutieren.

### Robustheit und Historizität von Phänomenen

Unter welchen Voraussetzungen ist es wenig überraschend, dass Replikationsversuche fehlschlagen? Eine Möglichkeit ist anzunehmen, dass die untersuchten Phänomene extrem empfindlich oder instabil seien. Regelmäßigkeiten im menschlichen Verhalten analog zu den Planetenbewegungen zu entdecken, könnte schlichtweg nicht möglich sein [@Smedslund.2015]. Die aktuelle Annahme vieler Sozialwissenschaftler ist die Existenz von Regelmäßigkeiten, die nicht jede Person ausnahmslos betreffen aber „im Schnitt" gelten. @Lewin.1930 unterscheidet diesbezüglich in *aristotelische* und *galileische* Gesetzmäßigkeiten, wobei die *aristotelischen* in den Sozialwissenschaften vorwiegend untersucht werden. Eine Regelmäßigkeit bzw. ein Naturgesetz im aristotelischen Sinne kann zum Beispiel sein, dass Männer größer als Frauen sind.

Noch extremer ist die Theorie, dass Menschen sich des Wissens über sie bewusst sind und ihr Verhalten dynamisch anpassen und Verhaltenswissenschaften immer historisch bzw. zeitgebunden sind: Wird herausgefunden, dass Menschen in ihren Entscheidungen tendenziell dazu neigen, nichts zu ändern, auch wenn sich dadurch ihre Situation verbessern würde, wird ihnen diese Tatsache über die Wissenschaft vor Augen geführt und sie können ihr Verhalten anpassen. Dabei handelt es sich übrigens um den Status Quo Bias, bei dem Menschen die jetzige Situation einer anderen vorziehen [@Samuelson.1988; @Xiao.2021]. Ein anderes Beispiel ist die Gender-Pay-Gap, also Gehaltsunterschiede zwischen Männern und Frauen unabhängig von der Qualifikation. Im Idealfall ändern Menschen das System, sobald sie von dem Problem wissen, dahingehend, dass die Gehaltsunterschiede nicht mehr existieren. Auf alle Bereiche der Sozialwissenschaften lässt sich diese Perspektive nicht übertragen. Beispielsweise hat das Wissen über die eigene Schmerzempfindlichkeit, Intelligenz, oder Persönlichkeit keinen Einfluss auf dieselbe.

Wie stark sich Phänomene durch vermeintlich kleinere Unterschiede im Versuchsaufbau unterscheiden, wurde bereits meta-wissenschaftlich untersucht. @Landy.2020 ließen mehrere Hypothesen von mehreren Forschenden prüfen und Faktoren, die laut den dahinterliegenden Theorien eigentlich keinen Unterschied machen sollten, führten dazu, dass Gegenteilige Ergebnisse entstanden. Auf Replikationsforschung übertragen ist es also möglich, dass in bestimmten Forschungsbereichen völlig unklar ist, unter welchen Bedingungen welche Zusammenhänge zu beobachten sind. Ein noch extremes Beispiel ist eine Untersuchung von @Breznau2022-du. Die Forschenden ließen 73 Gruppen dieselben Daten zum Testen der Hypothese "Immigration reduziert die öffentliche Unterstützung sozialpolitischer Maßnahmen" verwenden. Die Befunde variierten von großen negativen bis zu großen positiven Zusammenhängen und ließen sich nicht durch die methodischen Entscheidungen erklären. Sie empfehlen, Bescheidenheit bei der Erforschung komplexen menschlichen Verhalten walten zu lassen.

## Weiterführende Informationen

-   @Fleck.19352015 schlägt eine Theorie des wissenschaftlichen Fortschritts vor, bei der Wissen immer einem sogenannten Denkstil unterliegt, der für die jeweilige gesellschaftliche Situation optimal ist. Dabei bedient er sich Elementen der Evolutionstheorie, Soziologie, und Psychologie.

-   @shiffrin2018scientific diskutiert das scheinbare Paradox zwischen Fallibilität, also der Tatsache, dass Wissenschaft nicht immer richtig liegt, und wissenschaftlichem Fortschritt.

### Literatur
