---
title: "Karriere in der Wissenschaft"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Ein Beruf in der Wissenschaft setzt üblicherweise einen einschlägigen Studienabschluss (Bachelor und Master) voraus und beginnt mit einer Promotion. Im Rahmen der Promotion wird das wissenschaftliche Handwerk erlernt und der Doktor\*ingrad erlangt: Studien werden durchgeführt, Daten analysiert, und Forschungsartikel veröffentlicht. In vielen Fällen arbeiten Promovierende mit einer 50 -- 66% Stelle als wissenschaftliche Mitarbeiter\*innen, begutachten für ihre Vorgesetzten Artikel und Forschungsgelder-Anträge, schreiben eigene Anträge, verbringen mehrere Monate im Ausland, erstellen, beaufsichtigen, und korrigieren Klausuren, betreuen Abschlussarbeiten, und beteiligen sich an der universitären Selbstverwaltung durch die Teilnahme an Sitzungen und Mitgliedschaften bei Kommissionen. Zeitlich sind dabei bei Stellen oder Stipendien üblicherweise drei Jahre angesetzt. Am Anfang meiner Promotion sagte man mir, mit einer 40-Stunden-Woche schafft man es nicht, in der vorgesehenen Zeit zu promovieren -- 50% Gehalt für über 100% Arbeitszeit und einem befristeten Vertrag also. Verträge sind dabei jedoch nicht immer auf die Zeit der Promotion befristet. Viele wissen erst wenige Monate vor Vertragsende, wie viel Prozent Gehalt sie erhalten, wie umfangreich die Lehrverpflichtung ist, und wie lange der nächste Vertrag geht. Kurz: Die Arbeitsbedingungen sind nicht optimal und man muss ein hohes Maß an Flexibilität mitbringen, wenn man sich für den Weg in die Wissenschaft entscheidet.

### Doppelabhängigkeit

Für die Promotionsphase gibt es verschiedene Finanzierungsmöglichkeiten: Über Unternehmen lässt sich berufsbegleitend promovieren oder Stipendien zahlen über eine begrenzte Zeit Geld, das den Grunderhalt sichert (z.B. 1100€ über 36 Monate bei der Graduiertenförderung des Landes Sachsen-Anhalt, dazu kommen noch zusätzliche Kosten für die Sozialversicherung). Der häufigste Weg ist jedoch über eine Stelle als wissenschaftliche\*r Mitarbeiter\*in. Dabei ist die vorgesetzte Person diejenige Person, die auch die Promotionsarbeit bewertet. Die einem auferlegte Korrektur der 120 Erstsemester-Klausuren steht dann im Extremfall in Konflikt mit der Zeit, die für die Arbeit an der wissenschaftlichen Studie benötigt wird. Promovierende hängen also meistens von den betreuenden Professor\*innen in Form der Beschäftigung *und* über die Bewertung ihrer Arbeit ab, was also als *Doppelabhängigkeit* bezeichnet wird.

::: callout-tip
## Familienfeindliche Stipendien

Unbefristete Stellen, Doppelabhängigkeit oder geringfügige Stipendien, sowie Leistungsdruck haben klare negative Auswirkungen auf die Gesundheit der Forschenden und damit auf die Qualität der Wissenschaft. Wie sieht es mit Promotionsstipendien aus? Stipendien laufen oft 1 Jahr mit Option auf Verlängerung oder bis zu 3 Jahre. Forschende, die direkt nach der Schule und dem Studium promovieren, sind ca. 24 Jahre alt, haben eventuell einen Partner, und wünschen sich eine Familie. Im Rahmen ungewisser Vertragsverhältnisse ist das schwierig. Stipendien haben oft keine Möglichkeit zur Elternzeit und müssen dann pausiert werden -- oder sie laufen weiter und es wird keine zusätzliche Zeit angehängt. Sie verbieten zusätzliches Einkommen, weshalb das Elterngeld dann auf den dafür angesetzten Mindestbetrag fällt. Zusätzlich schreiben Sie vor, dass die geförderte Person *inklusive Ehepartner* ein bestimmtes Maximalvermögen nicht überschreiten darf, sodass auch keine Finanzierung durch mögliche Rücklagen klappt.
:::

### Depressionen, Burnout, und #IchbinHanna

Fächerübergreifend hat sich als Antwort auf ein inzwischen gelöschtes Erklärvideo vom Bundesministerium für Bildung und Forschung zum Wissenschaftszeitvertragsgesetz (WissZeitVG) eine Bewegung unter dem Hashtag #IchbinHanna entwickelt, die die dortige sachliche Erklärung (<https://www.youtube.com/watch?v=PIq5GlY4h4E>) und die Arbeitsbedingungen in der Wissenschaft stark kritisiert. Es heißt „damit auch nachrückende Wissenschaftlerinnen und Wissenschaftler die Chance auf den Erwerb dieser Qualifizierung haben und nicht eine Generation alle Stellen verstopft, dürfen Hochschulen und Forschungseinrichtungen befristete Verträge nach den besonderen Regeln des WissZeitVG abschließen. So kommt es zur Fluktuation und die fördert die Innovationskraft". 90% aller Wissenschaftler\*innen sind unbefristet angestellt (<https://www.youtube.com/watch?v=H1wJmqpGhJc>).

Planungsunsicherheit und massiver Konkurrenzdruck fördern die Innovationskraft? Das scheint unwahrscheinlich: Unter Forschenden mentale Erkrankungen wie Burnout [@Jaremka.2020] und Anzeichen für Angststörungen und Depression stark verbreitet. Einer Überblicksstudie von @Satinsky.2021 zufolge, leiden zwischen 18 und 31% der Promovierenden unter Depressionen.

::: callout-caution
## Wer hilft?

Schnelle Hilfe bei psychischen Problemen leistet beispielsweise das Krisentelefon der [TelefonSeelsorge](https://www.telefonseelsorge.de). Manche Universitäten haben spezifische Anlaufstellen, Städte haben häufig örtliche Psychotherapie-Ambulanzen und Beratungsstellen.
:::

### Top-Down-Wandel

Diejenigen, die das System ändern können, also alle mit unbefristeten Verträgen, leiden nicht mehr unter ihm. Für diejenigen, die unter dem System leiden, ist es unklug, das System ändern zu wollen und sich an die Professor\*innen zu wenden, denn das sind die Leute, die über ihren späteren Verbleib in der Wissenschaft im Rahmen von Berufungskommissionen bei der Entscheidung der Vergabe von Professuren entscheiden. Im Extremfall kann das dazu führen, dass jemand Kritik an Arbeiten von Wissenschaftler\*innen in höheren Positionen aus Angst, die eigenen Chancen auf eine Professur zu schmälern, zurückfährt. Auf der anderen Seite haben Professor\*innen bewiesen, dass sie sehr gut nach den Spielregeln spielen können. Zuzugeben, dass sie eine der seltenen und heiß begehrten Stellen nicht über Qualität sondern Quantität ihrer Forschung erhalten haben, hieße, sich selbst abzuwerten.

### Literatur
