---
title: "Wandel im System"
editor: visual
format: html
bibliography: references.bib
bibliographystyle: apa
---

Seit dem Bekanntwerden der geringen Replizierbarkeit psychologischer Studien wurde das wissenschaftliche System in vielen Aspekten hinsichtlich seiner Offenheit und Transparenz verändert. Einige Zeitschriften setzen für die Veröffentlichung wissenschaftlicher Artikel voraus, dass die Daten öffentlich zugänglich sind beziehungsweise erklärt ist, weshalb das nicht der Fall ist (z.B. bei Daten, die sich schwierig anonymisieren lassen). In seltenen Fällen wie bei der Zeitschrift Meta-Psychology rechnen Wissenschaftler\*innen alle Ergebnisse nach. Als Antithese zum "Impact Factor", einer Kennzahl, die angibt wie oft eine Zeitschrift zitiert wird und nachweislich nichts mit der Qualität der darin enthaltenen Forschung zu tun hat [@Brembs.2018], wurde der TOP-Factor eingeführt (TOP: Transparency and Openness Promotion). Dieser gibt für eine Liste von Kriterien an, in welchem Maße sie von verschiedenen Zeitschriften erfüllt werden. In anderen Feldern wie Betriebswirtschaftslehre oder Marketing werden Zeitschriften sogar von wenigen ausgewählten Forschenden über Ratingskalen bewertet, die jährlich als Rankings veröffentlicht werden. TOP-Factors hingegen sind objektiv, werden stetig aktualisiert, und sind unter topfactor.org öffentlich einsehbar und nachvollziehbar. Für jeden Faktor gibt es vier Stufen: Keine erwähnung, Level 1, Level 2, und Level 3. Level 3 ist dabei das Ideal, zum Beispiel hieße das im Hinblick auf Transparenz von Daten, dass ein Artikel erst dann veröffentlicht wird, wenn die Daten öffentlich verfügbar sind und die Analysen von einer unabhängigen Person erfolgreich nachgerechnet (*reproduziert*) wurden. Zum Scoring einer Zeitschrift werden für die Levels 1-3 entsprechende Punkte vergeben und aufsummiert.[^wandel-1]

[^wandel-1]: Sozialwissenschaftler\*innen wissen, dass das Aufsummieren der Werte unsinnig ist, da Level 2 nicht "doppelt so gut" wie Level 1 ist, und die verschiedenen Faktoren nicht immer gleich gewichtet werden sollten - rechnerisch wird aber genau das angenommen. Als heuristische Schätzung der Offenheit von Zeitschriften ist dieses Vorgehen jedenfalls sinnvoller als bibliometrische Maße.

| Faktor                                                           | Erklärung                                                                                                                                                                                                                                                                                                                                                                                                                  |
|------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Zitation von Daten                                               | Den meisten Forschungsartikeln liegen Daten zugrunde. Spezifisch geht es hier um die Möglichkeit, Daten unabhängig von den Artikeln zitieren zu können (z.B. über eine eigene Kennung, wie ein *Digital Object Identifier* \[DOI\]).                                                                                                                                                                                       |
| Transparenz von Daten                                            | Wenn möglich sollten Daten veröffentlicht werden. Das ist direkt über Fachzeitschriften oder über sogenannte *Forschungsdaten-Repositorien* möglich.                                                                                                                                                                                                                                                                       |
| Transparenz vom Analyse-Code                                     | Mit dem Analyse-Code werden die Forschungsdaten ausgewertet. Andere Forschende sollten die Möglichkeit haben, den Code auszuführen und die Ergebnisse zu *reproduzieren* bzw. zu prüfen.                                                                                                                                                                                                                                   |
| Transparenz der Forschungsmaterialien                            | Bei Forschungsmaterialien kann es sich um Fragebögen, gezeigte Bilder oder Filme, aber auch präsentierte Gerüche, verkostete Früchte, oder Programme handeln. Wenn möglich, sollten auch sie (in digitaler Form) in einem Repositorium abgelegt werden. Das ist bei Gegenständen selbstverständlich nicht möglich. Bei Genen gibt es beispielsweise *alphanumerische Codes*, mittels welchen sich Forschende verständigen. |
| Richtlinien zum Beschreiben des Versuchsaufbaus und der Analysen | Zum Verständnis aber auch zur Nachbildung einer Studie ist es wichtig, den Versuchsaufbau genau zu beschreiben. Einige Zeitschriften haben in den letzten Jahren beispielsweise die Wortbegrenzung für die entsprechende Abschnitte in Forschungsartikeln aufgehoben.                                                                                                                                                      |
| Präregistrierung von Studien                                     | Siehe auch Abschnitt zu Präregistrierungen in diesem Buch: Sofern eine Studie Hypothesen testet (also z.B. Erwartungen oder Vorhersagen für das Ergebnis), sollten diese im Vorhinein festgelegt sein und nach dem Sehen der Ergebnisse nicht an diese angepasst werden. Idealerweise fordern Fachzeitschriften für solche Studien Präregistrierungen und verpflichten Forschende den Link zu ihnen anzugeben.             |
| Präregistrierung des Analyseplans                                | Der Weg von den Daten zu den Ergebnissen ist ein langer. Die Ergebnisse hängen von vielen Entscheidungen ab. Um sich dieser Flexibilität zu berauben, sollten Forschende den Analyseplan in der Präregistrierung beschreiben.                                                                                                                                                                                              |
| Replikation                                                      | Trotz ihres Wertes gibt es noch immer viele Zeitschriften, die keine Replikationsstudien veröffentlichen. Im Mindestfall ermutigen Zeitschriften Forschende dazu, Replikationsstudien bei ihnen einzureichen.                                                                                                                                                                                                              |

: Übersicht über TOP Richtlinien

Am Wandel beteiligt sind vor allem Jungwissenschaftler\*innen oder Forschende im frühen Karrierestadium (*Early Career Researchers*). An vielen Universitäten haben sich in den letzten Jahren Open Science Initiativen oder regelmäßige Treffen („Reproducibili-Tea") herausgebildet, die fast ausschließlich aus "Post Docs" (Personen nach der Promotion ohne Professur), Promovierenden (Doktoranden), und Studierenden bestehen. In Deutschland haben sie sich zum NOSI (Netzwerk der Open Science Initiativen Deutschland) vernetzt (REF OSF Link). ~~Besonders hervorzuheben ist das Journal of European Psychology Students (REF LINK), das vollständig von Studierenden geführt wird, ausschließlich Artikel mit studentischen Erstautor\*innen veröffentlicht, und dessen TOP-Factor den zahlreicher prestigereicher Zeitschriften übersteigt (XXX Beispiel, Stand: 24.10.22).~~

### Hat sich die Replizierbarkeitsrate erhöht?

Die Replikationskrise dauert nun schon ungefähr ein Jahrzehnt an und einiges hat sich geändert. Ist dadurch auch das Problem der Replizierbarkeit gelöst? Zum einen ist für viele Bereiche noch gar nicht klar, was sich replizieren lässt. Im Marketing führte eine Zeitschrift kurzzeitig eine Replikationsecke ein (JOURNAL NAME XXX siehe Susi paper p-values p-bullshit). Diese wurde dann in eine andere, weniger bekannte Zeitschrift verlagert. Die andere Zeitschrift wurde dann XXX. Aktuell sind Projekte in Arbeit, die die Replizierbarkeit schätzen, die Ergebnisse sind größtenteils noch vorläufig und unklar. In einem eigenen Projekt, sammeln wir Replikationsergebnisse, um langfristig je Disziplin und über die Zeit zu schauen, wie sich Replikationsraten verändert haben. Tagesaktuelle Werte sind online verfügbar (<https://metaanalyses.shinyapps.io/replicationdatabase/>). Eine Evaluation über mehrere Disziplinen und Jahre erfordert noch hunderte weitere Replikationsstudien.

### Die Open Science Revolution als Paradigmenwechsel[\[LR8\]](#_msocom_8) 

Wissenschaftshistoriker oder -theoretiker beschreiben die Entwicklung der Wissenschaft als nicht-stetig. Lehrbücher werden nicht immer dicker, stattdessen werden manche Kapitel kürzer, weil das darin beschriebene Wissen verworfen wird, andere werden dicker, weil neue Erkenntnisse hinzukommen. Zeitweise verschwinden Kapitel sogar vollständig. Eines der bekanntesten Wissenschaftsmodelle stammt von Thomas Kuhn (REF), der selbst Psychologe war und große Teile vom Mediziner und Soziologen Ludwik Fleck (REF) übernommen hat (siehe Abbildung X). Darin wird angenommen, dass zeitweise das Wissen wächst, sich jedoch dabei Befunde anhäufen, die mit allem anderen Wissen nicht vereinbar sind. Diese sogenannten Anomalien lassen sich ab einem bestimmten Punkt nicht mehr ignorieren. Ab dort kippt das wissenschaftliche Weltbild: Neue Theorien werden entworfen, die die Anomalien erklären können und altes Wissen wird verworfen oder in die neuen Theorien integriert. Dieses Kippen wird als Paradigmenwechsel oder wissenschaftliche Revolution bezeichnet[\[3\]](#_ftn3). Paradebeispiel für so einen Paradigmenwechsel ist der Übergang vom geozentrischen zum heliozentrischen Weltbild in der Astronomie, die Prospect Theory in den Wirtschaftswissenschaften, oder, so die Behauptung hier im Buch: Die Replikationskrise in der Psychologie. Anomalien sind in diesem Fall die Befunde von Bem oder Bargh oder vereinzelte Replikationsfehlschläge. Sie waren mit bisherigem Wissen nicht vereinbar und nachdem sich viele solcher Befunde häuften, ließen sie sich nicht mehr ignorieren oder abtun. Dass die Replikationsforscher\*innen etwas falsch gemacht hatten, nicht qualifiziert waren, oder Pech hatten, war keine gute Erklärung mehr. Im Gegensatz zu klassischen Revolution steht bei der Open Science Revolution keine bestimmte Theorie oder Forschungsdisziplin die verworfen wird im Fokus, sondern die wissenschaftliche Methode und das Wissenschaftssystem der Sozialwissenschaften. In Anlehnung an die wissenschaftstheoretische Terminologie von Kuhn wird neben Replikationskrise auch Glaubwürdigkeits-Revolution (Credibility Revolution; REF <https://www.nature.com/articles/s44271-023-00003-2>) verwendet. Für [\[LR9\]](#_msocom_9) philosophische Betrachtungen siehe auch REF <https://osf.io/preprints/metaarxiv/2dz9s/> .

ABBILDUNG X: PARADIGMENWECHSEL
